get app installation id

diff --git a/.github/workflows/provision-runners.yml b/.github/workflows/provision-runners.yml
--- a/.github/workflows/provision-runners.yml
+++ b/.github/workflows/provision-runners.yml
@@ -39,15 +39,45 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
+      - name: Install jwt-cli
+        run: |
+          latest_version=$(curl -s https://api.github.com/repos/mike-engel/jwt-cli/releases/latest | grep tag_name | cut -d '"' -f 4) && \
+          curl -L -o jwt-cli https://github.com/mike-engel/jwt-cli/releases/download/$latest_version/jwt-linux.tar.gz && \
+          tar -xvf jwt-cli && \
+          mv jwt /usr/local/bin/jwt && \
+          chmod +x /usr/local/bin/jwt
+
       - name: Generate access token
         id: generate-access-token
-        uses: actions/create-github-app-token@v1
-        with:
-          app-id: ${{ vars.GH_APP_ID }}
-          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
-          owner: ${{ github.repository_owner }}
-          skip-token-revoke: true
-      
+        run: |
+          echo "${{ secrets.GH_APP_PRIVATE_KEY }}" > /tmp/private-key.pem
+          gh_app_token=$(jwt encode --exp=$(($(date +%s)+600)) --alg RS256 --iss ${GH_APP_ID} --secret @/tmp/private-key.pem)
+          rm /tmp/private-key.pem
+
+          installation_id=$(curl --fail -X GET \
+              -H "Authorization: Bearer $gh_app_token" \
+              -H "Accept: application/vnd.github+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              "https://api.github.com/orgs/${{ github.repository_owner }}/installation" | jq .[0].id)
+          
+          # if the installation id length is <1, then we exit
+          if [ ${#installation_id} -lt 1 ]; then
+            echo "Failed to get installation id"
+            exit 1
+          fi
+            
+          echo installation_id=$installation_id >> $GITHUB_OUTPUT
+
+          # get access token for installation
+          installation_access_token=$(curl --fail -X POST \
+              -H "Authorization: Bearer ${gh_app_token}" \
+              -H "Accept: application/vnd.github+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              "https://api.github.com/app/installations/${installation_id}/access_tokens" | jq .token --raw-output)
+          
+          echo token=$installation_access_token >> $GITHUB_OUTPUT
+
+
       - name: Get GH App installation ID
         id: get-installation-id
         run: |
@@ -55,7 +85,7 @@ jobs:
               -H "Authorization: Bearer ${{ steps.generate-access-token.outputs.token }}" \
               -H "Accept: application/vnd.github+json" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
-              "https://api.github.com/app/installations" | jq .[0].id)
+              "https://api.github.com/orgs/${{ github.repository_owner }}/installation" | jq .[0].id)
           
           # if the installation id length is <1, then we exit
           if [ ${#installation_id} -lt 1 ]; then
@@ -88,6 +118,6 @@ jobs:
             useJobs=${{ inputs.useJobs }}
             runnerLabels=${{ inputs.runnerLabels }}
             gitHubAppId=${{ vars.GH_APP_ID }}
-            gitHubAppInstallationId=$installation_id
+            gitHubAppInstallationId=${{ steps.generate-access-token.outputs.installation_id }} 
             keyVaultUrl=${{ inputs.keyVaultUrl }}
           deploymentName: deploy-aca-gh-runners-app
