get github app id

diff --git a/.github/workflows/provision-runners.yml b/.github/workflows/provision-runners.yml
--- a/.github/workflows/provision-runners.yml
+++ b/.github/workflows/provision-runners.yml
@@ -56,6 +56,13 @@ jobs:
               -H "Accept: application/vnd.github+json" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               "https://api.github.com/app/installations" | jq .[0].id)
+          
+          # if the installation id length is <1, then we exit
+          if [ ${#installation_id} -lt 1 ]; then
+            echo "Failed to get installation id"
+            exit 1
+          fi
+            
           echo installation_id=$installation_id >> $GITHUB_ENV
 
       - name: Azure Login
